# Generated by Django 2.2.9 on 2020-04-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_profile',
            name='member_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
