# Generated by Django 2.2.9 on 2020-04-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_member_profile_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_profile',
            name='is_approved',
        ),
    ]
