# Generated by Django 2.2.9 on 2020-04-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_remove_member_profile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_profile',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member_profile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='True means Administrator has allowed member to join'),
        ),
        migrations.AddField(
            model_name='member_profile',
            name='member_bio',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member_profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional, used for making contact outside of app', max_length=15),
        ),
        migrations.AddField(
            model_name='member_profile',
            name='state',
            field=models.CharField(blank=True, help_text='Use standard 2-character codes', max_length=2),
        ),
        migrations.AddField(
            model_name='member_profile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
