# Generated by Django 2.2.9 on 2020-04-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_auto_20200425_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_profile',
            old_name='zipcode',
            new_name='zip_code',
        ),
    ]
