# Generated by Django 2.2.9 on 2020-04-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_auto_20200425_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_profile',
            name='member_id',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
