# Generated by Django 2.2.9 on 2020-05-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_auto_20200425_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('member_id', models.PositiveSmallIntegerField(help_text='Providing member')),
                ('type', models.CharField(choices=[('Service', 'service'), ('Perishable Food', 'perishable_food'), ('Non Perishable Food', 'non_perishable_food'), ('Products', 'products'), ('Financial', 'financial'), ('Other', 'other')], max_length=25)),
                ('frequency', models.CharField(choices=[('Daily', 'daily'), ('Weekly', 'weekly'), ('Monthly', 'monthly'), ('Intermittent', 'intermittent'), ('NA', 'Not Applicable')], help_text='Used for items that repeat (i.e. at service that can be provided     to one person every week', max_length=25)),
                ('expiration_date', models.DateTimeField(blank=True, help_text='useful for food and deadlines')),
                ('provided_to', models.PositiveSmallIntegerField(blank=True, help_text='Member who received the service')),
            ],
            options={
                'ordering': ['type', 'expiration_date'],
            },
        ),
    ]
