# Generated by Django 2.2.9 on 2020-05-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0008_auto_20200502_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provision',
            name='member_id',
            field=models.PositiveSmallIntegerField(default=0, help_text='Providing member'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='provided_to',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Member who received the service', null=True),
        ),
    ]
