# Generated by Django 2.2.9 on 2020-05-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0009_auto_20200502_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='provision',
            name='status',
            field=models.CharField(choices=[('Available', 'available'), ('Pending', 'pending'), ('Provided', 'provided')], default='one_time', help_text='Used for items that repeat (i.e. at service that can be provided     to one person every week', max_length=25),
        ),
        migrations.AlterField(
            model_name='provision',
            name='frequency',
            field=models.CharField(choices=[('One Time', 'one_time'), ('Daily', 'daily'), ('Weekly', 'weekly'), ('Monthly', 'monthly'), ('Intermittent', 'intermittent'), ('NA', 'Not Applicable')], default='one_time', help_text='Used for items that repeat (i.e. at service that can be provided     to one person every week', max_length=25),
        ),
        migrations.AlterField(
            model_name='provision',
            name='type',
            field=models.CharField(choices=[('Service', 'service'), ('Perishable Food', 'perishable_food'), ('Non Perishable Food', 'non_perishable_food'), ('Product', 'product'), ('Financial', 'financial'), ('Other', 'other')], max_length=25),
        ),
    ]
