# Generated by Django 2.2.9 on 2020-05-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0010_auto_20200502_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provision',
            name='provided_to',
        ),
        migrations.AddField(
            model_name='provision',
            name='created_at',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
