# Generated by Django 2.2.9 on 2020-05-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0011_auto_20200504_0740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provision',
            options={},
        ),
        migrations.RemoveField(
            model_name='provision',
            name='created_at',
        ),
    ]
