# Generated by Django 2.2.9 on 2020-05-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0012_auto_20200504_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_profile',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
