# Generated by Django 2.2.9 on 2020-05-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0017_auto_20200507_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='provision',
            name='provided_to',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Member who received the service', null=True),
        ),
    ]
