# Generated by Django 2.2.9 on 2020-05-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0018_provision_provided_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('member_id', models.PositiveSmallIntegerField(default=0, help_text='Member with need')),
                ('type', models.CharField(choices=[('Service', 'service'), ('Perishable Food', 'perishable_food'), ('Non Perishable Food', 'non_perishable_food'), ('Product', 'product'), ('Financial', 'financial'), ('Other', 'other')], max_length=25)),
                ('due_date', models.DateTimeField(blank=True, help_text='when is the item needed?', null=True)),
                ('background_info', models.TextField(blank=True, help_text='Any additional information that might help', max_length=1000)),
                ('provided_from', models.PositiveSmallIntegerField(blank=True, help_text='Member who provided the service', null=True)),
            ],
        ),
    ]
