# Generated by Django 2.2.9 on 2020-05-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0021_auto_20200513_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='status',
            field=models.CharField(choices=[('Open', 'open'), ('Pending', 'pending'), ('Provided', 'provided'), ('Expired', 'expired'), ('Retracted', 'retracted')], default='open', max_length=25),
        ),
        migrations.AlterField(
            model_name='provision',
            name='status',
            field=models.CharField(choices=[('Available', 'available'), ('Pending', 'pending'), ('Provided', 'provided'), ('Expired', 'expired'), ('Retracted', 'retracted')], default='available', max_length=25),
        ),
    ]
