# Generated by Django 2.2.9 on 2020-05-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0022_auto_20200516_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='status',
            field=models.CharField(choices=[('Open', 'open'), ('Pending', 'pending'), ('Provided', 'provided'), ('Expired', 'expired'), ('Retracted', 'retracted')], default='Open', max_length=25),
        ),
    ]
