# Generated by Django 2.2.9 on 2020-05-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0024_auto_20200519_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Provided', 'Provided'), ('Expired', 'Expired'), ('Retracted', 'Retracted')], default='Open', max_length=25),
        ),
        migrations.AlterField(
            model_name='need',
            name='type',
            field=models.CharField(choices=[('Service', 'Service'), ('Perishable Food', 'Perishable Food'), ('Non Perishable Food', 'Non Perishable Food'), ('Product', 'Product'), ('Financial', 'Financial'), ('Other', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='provision',
            name='frequency',
            field=models.CharField(choices=[('One Time', 'One_time'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Intermittent', 'Intermittent'), ('Not Applicable', 'Not Applicable')], default='one_time', help_text='Used for items that repeat (i.e. at service that can be provided     to one person every week', max_length=25),
        ),
        migrations.AlterField(
            model_name='provision',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Provided', 'Provided'), ('Expired', 'Expired'), ('Retracted', 'Retracted')], default='available', max_length=25),
        ),
        migrations.AlterField(
            model_name='provision',
            name='type',
            field=models.CharField(choices=[('Service', 'Service'), ('Perishable Food', 'Perishable Food'), ('Non Perishable Food', 'Non Perishable Food'), ('Product', 'Product'), ('Financial', 'Financial'), ('Other', 'Other')], max_length=25),
        ),
    ]
