# Generated by Django 2.2.9 on 2020-05-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0025_auto_20200519_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provision',
            name='frequency',
            field=models.CharField(choices=[('One Time', 'One_time'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Intermittent', 'Intermittent'), ('Not Applicable', 'Not Applicable')], default='One_time', help_text='Used for items that repeat (i.e. at service that can be provided     to one person every week', max_length=25),
        ),
        migrations.AlterField(
            model_name='provision',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Provided', 'Provided'), ('Expired', 'Expired'), ('Retracted', 'Retracted')], default='Available', max_length=25),
        ),
    ]
