# Generated by Django 2.2.9 on 2020-05-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0026_auto_20200522_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], default='Open', max_length=25)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
