# Generated by Django 2.2.9 on 2020-05-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0027_action_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action_items',
            new_name='Action_item',
        ),
    ]
