# Generated by Django 2.2.9 on 2020-05-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0028_auto_20200525_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action_item',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Rejected', 'Rejected'), ('OBEd', 'OBEd')], default='Open', max_length=25),
        ),
    ]
